name: PVS Test action
description: This file ... # TODO: Complete description later
inputs:
  TDV_ENV:
    description: TDV Environment
    required: true
  TDV_USERNAME:
    description: TDV DEV Username
    required: true
  TDV_PASSWORD:
    description: TDV DEV Password
    required: true
  DIRECTORY_LIST:
    description: Directories List
    required: true
  FOLDER_LIST:
    description: Folder List
    required: true
    
runs:
  using: "composite"
  steps:
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    - name: Install dependencies
      run: |
        set -x
        python -m pip install --upgrade pip
        pip install poetry==1.7.1
        poetry -C ${{ github.action_path }} install
      shell: bash
    - name: run python script
      shell: bash
      env:
        TDV_ENV: ${{ inputs.TDV_ENV }}
        TDV_USERNAME: ${{ inputs.TDV_USERNAME }}
        TDV_PASSWORD: ${{ inputs.TDV_PASSWORD }}
        DIRECTORY_LIST: ${{ inputs.DIRECTORY_LIST }}
        FOLDER_LIST: ${{ inputs.FOLDER_LIST }}
      run: |
        poetry -C ${{ github.action_path }} run pvs_testing
